// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperTrigger.Web.Data;

#nullable disable

namespace SuperTrigger.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616073832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.AdPrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdPrincipals");
                });

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.FileTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessDepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameContains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileTriggers");
                });

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.MailTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentsType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyFilterContains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomMailServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomMailServerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedMailBox")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectFilterContains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MailTriggers");
                });

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.OrchSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthNewMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CyberArkSDKFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAppScopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailServerURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailServerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MailTriggerIntervalInMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("OrchestratorGeneralFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrchestratorMainFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrchestratorURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SSO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SameFileIntervalInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseDefaultProxy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrchSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthNewMethod = false,
                            CyberArkSDKFilePath = "",
                            ExternalAppScopes = "OR.Assets.Read,OR.Queues",
                            MailServerURL = "",
                            MailServerVersion = "Exchange2013_SP1",
                            MailTriggerIntervalInMinutes = 0.5,
                            OrchestratorGeneralFolderName = ".General",
                            OrchestratorMainFolderName = "Root",
                            OrchestratorURL = "",
                            Password = "",
                            SSO = false,
                            SameFileIntervalInSeconds = 20,
                            TenantName = "",
                            UseDefaultProxy = false,
                            Username = ""
                        });
                });

            modelBuilder.Entity("SuperTrigger.Web.Data.Entities.QueueItemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QueueItemLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
